# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 931826e3646591324bbcdd6f03e5ade3513c74627b3678b561ba53312f2413525814bbe6260c39d121b739877a19024a1cd5dc3d842305dc97c63cee0eb8fc3b

test:
  secret_key_base: be2870d505d5bcc382a0c7ed2bd978b954362cf409e90da8e534ef63e960917f1f9084a7e1e61abf58a6cb96512fd0eff5bbd60523cb19b2bb87e5fe5e2f1482

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
